Closes #11 – Test for completing order with payment type passes
nss-day-cohort-48/bangazon-gqgonzales pull request #35
Opened 2021-09-02 20:25 UTC by gqgonzales

Description of PR that completes issue here...

## Changes

- In `bangazonapi/views/order.py `, carried over PaymentSerializer, which enables id of payment type to be accessible in an order dictionary
- In `tests/order.py `, created test to check if the addition of a payment type would close an order
- In `tests/order.py `, improved set up and removed redundancies of things like auth token checks

## Testing

Description of how to test code...

- [ ] Run migrations
- [ ] Run test suite
- [ ] Seed database
- [ ] In terminal, run `python manage.py test tests.order -v 1`
- [ ] Confirm three tests are passing

## Related Issues

- Closes #11

2021-09-02 21:15 UTC, heymonicakay requested changes
Great work! Just a small change requested here to remove that extra model import. Ping me when you push up changes so I can approve!

2021-09-02 21:15 UTC, heymonicakay commented on bangazonapi/views/order.py
> +from bangazonapi.models import Order, Payment, Customer, Product, OrderProduct, payment
your Payment model is already being imported, so you don't need to import `payment`

2021-09-03 15:57 UTC, gqgonzales commented
Fixed changes from Monica, re-requesting review from Gwynne and Hannah.

2021-09-03 20:24 UTC, hannahhall approved these changes
👍

2021-09-03 20:25 UTC, merged