6 report expensive products
nss-day-cohort-48/bangazon-gqgonzales pull request #38
Opened 2021-09-03 19:13 UTC by gqgonzales

Description of PR that completes issue here...

## Changes

- Added app `bangazonreports` and necessary files for generating reports
- Added necessary SQL for querying database for expensive products

## Testing

Description of how to test code...

- [ ] Run migrations
- [ ] Run test suite
- [ ] Seed database with `./seed_data.sh`
- [ ] Run `python manage.py runserver`
- [ ] Navigate to `http://localhost:8000/reports/expensiveproducts` in a browser
- [ ] Confirm report contents

## Related Issues

- Fixes #6

2021-09-03 21:52 UTC, hannahhall requested changes
Looks good just a minor change to the sql query

2021-09-03 21:52 UTC, hannahhall commented on bangazonreports/views/products/expensiveproducts.py
> +                    JOIN bangazonapi_customer c ON p.customer_id = c.id
No need to join with customer or user. Sql query should only have info about the product

2021-09-03 23:11 UTC, gqgonzales commented on bangazonreports/views/products/expensiveproducts.py
> +                    JOIN bangazonapi_customer c ON p.customer_id = c.id
Fixed it!

2021-09-07 14:33 UTC, hannahhall approved these changes
👍

2021-09-07 14:56 UTC, merged